### ISSUE TITLE
Source of Download Data

### ISSUE THREAD

**Issue by zeke** [hughsk/npm-stats#6]
It looks like npm-stats' download data is coming from couch:

https://github.com/zeke/npm-stats/blob/4d05a27c8702ccc74562b6527b896cb286bc0c44/lib/module.js#L28-L37

But as @seldo has informed me, the canonical source of download data is now:

https://github.com/npm/download-counts#readme

Any thoughts, @hughsk? Should I update npm-stats to get data from download-counts instead?

**Comment by hughsk** [comment]
Fixed in #3 :)

**Comment by zeke** [comment]
:cake:

:wave:
